Firma.PortalWWW/Controllers/SklepController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Firma.Data.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Firma.PortalWWW.Controllers
{
    public class SklepController : Controller
    {
        private readonly FirmaContextB _context; // tak tworzymy połączenie z bazą danych
        public SklepController(FirmaContextB context)
        {
            _context = context; // tu inicjalizujemy baze danych
        }


        public async Task<IActionResult> Index(int? id) // w id będzie przechowywny id rodzaju którego towary mmy wyświetlić
        {
            //do ViewBag zapisuję wszystkie rodzaje z bazy danych asynchronicznie (musimy użyć using Microsoft.EntityFrameworkCore;)
            ViewBag.Rodzaje = await _context.Rodzaj.ToListAsync();


            ViewBag.ModelStrony =
              (
              from strona in _context.Strona // dla każdej strony z bazy danych stron
              orderby strona.Pozycja // posortowanej względem pozycji
              select strona // wybieramy stronę
              ).ToList();
            ViewBag.ModelAktualnosci =
                (
                from aktualnosc in _context.Aktualnosc // dla każdej strony z bazy danych stron
                orderby aktualnosc.Pozycja // posortowanej względem pozycji
                select aktualnosc // wybieramy stronę
                ).ToList();
            ViewBag.ModelParametry =
                (
                from parametr in _context.Parametr // dla każdej strony z bazy danych stron
                orderby parametr.IdParametru // posortowanej względem pozycji
                select parametr // wybieramy stronę
                ).ToList();
            ViewBag.ModelTowary =
                (
                from towar in _context.Towar // dla każdej strony z bazy danych stron
                orderby towar.IdTowaru // posortowanej względem pozycji
                select towar // wybieramy stronę
                ).ToList();

            ViewBag.ModelProdukty2 =
               (
               from produkt in _context.Produkt2 // dla każdej strony z bazy danych stron
               orderby produkt.IdProduktu2 // posortowanej względem pozycji
               select produkt // wybieramy stronę
               ).ToList();


            //przy pierwszym uruchomieniu sklepu nie ma wybranego rodzaju więc pod rodzaj podstawimy pierwszy rodzaj z bazy danych
            if (id == null)
            {
                var pierwszy = await _context.Rodzaj.FirstAsync();
                id = pierwszy.IdRodzaju;
            }
            //do widoku przekazuję wszytskie towary danego rodzaju ktróego mamy id asynchronicznie
            return View(await _context.Produkt2.Where(item => item.IdRodzaju == id).ToListAsync());
        }

        //funkcja zwraca do widoku towar o id danym jako parametr

        public async Task<IActionResult> Szczegoly(int id)
        {
            ViewBag.Rodzaje = await _context.Rodzaj.ToListAsync();
            return View(await _context.Produkt2.Where(t => t.IdProduktu2 == id).FirstOrDefaultAsync());
        }
    }
}

Firma.PortalWWW/Views/Shared/Aktualnosci.cshtml
@model IEnumerable<Firma.Data.Data.CMS.Aktualnosc>

<h1 class="center">Aktualności</h1>
<div class="carousel carousel-slider center">
    <div class="carousel-fixed-item center">
        <a class="btn waves-effect white grey-text darken-text-2">button</a>
    </div>
    <div class="carousel-item red white-text" href="#one!">
        <h2>First Panel</h2>
        <p class="white-text">This is your first panel</p>
    </div>
    <div class="carousel-item amber white-text" href="#two!">
        <h2>Second Panel</h2>
        <p class="white-text">This is your second panel</p>
    </div>
    <div class="carousel-item green white-text" href="#three!">
        <h2>Third Panel</h2>
        <p class="white-text">This is your third panel</p>
    </div>
    <div class="carousel-item blue white-text" href="#four!">
        <h2>Fourth Panel</h2>
        <p class="white-text">This is your fourth panel</p>
    </div>
</div>

<div class="row g-0"><ul>
    @foreach (var item in Model.TakeLast(3))
    {
        <li class="list-group-item">
   
            <div class="col s12 m4">
                <div class="card medium blue-grey lighten-4">
                    <div class="card-image waves-effect waves-block waves-light">
                        <img src=@item.FotoURL>
                    </div>
                    <div class="card-content">
                        <h6 class="card-title">@item.Tytul</h6>
                        <p>@item.Tresc</p>
                        <p class="card-text"><small class="text-muted">Dodano @item.DataAktualna.ToShortDateString()</small></p>
                    </div>
                </div>
            </div>
        </li>
    }
</ul>
</div>




@*<div class="col s4 ">
        <div class="card">
            <div class="card-image">
                <img src="https://ecsmedia.pl/c/pozniej-b-iext68952603.jpg">
            </div>
            <div class="card-content">
                <p>
                    I am a very simple card. I am good at containing small bits of information.
                    I am convenient because I require little markup to use effectively.
                </p>
            </div>
            <div class="card-action center-align">
                <a class="black-text button__p default">Dodaj do koszyka</a>
            </div>
        </div>
    </div>
    <div class="col s4 ">
        <div class="card ">
            <div class="card-image">
                <img src="https://ecsmedia.pl/c/pozniej-b-iext68952603.jpg">
            </div>
            <div class="card-content">
                <p>
                    I am a very simple card. I am good at containing small bits of information.
                    I am convenient because I require little markup to use effectively.
                </p>
            </div>
            <div class="card-action center-align">
                <a class="black-text button__p default">Dodaj do koszyka</a>
            </div>
        </div>
    </div>*@

Firma.PortalWWW/Views/Shared/Odnosniki.cshtml
@model IEnumerable<Firma.Data.Data.CMS.Strona>
<div class="nav-wrapper">
    <a id="logo-container" href="#" class="brand-logo logo">
        <i class="material-icons">spa</i>Biblioteka
    </a>
    <ul class="right hide-on-med-and-down margin__right">
        <li class="border border-dark black-text">@Html.ActionLink("Strona główna", "Index", "Home")</li>
        @foreach (var item in Model)
        {
            @*<li>
                @Html.ActionLink(item.Tytul, "Index", "Home", new { id = item.IdStrony }, null)
            </li>*@
            <li>
                @Html.ActionLink(item.Tytul, "Index", "Home", new { id = item.IdStrony }, null)
            </li>
        }
        @*<li>
            @Html.ActionLink("O nas", "About", "Home")
        </li>
        <li>
            @Html.ActionLink("Polityka prywatności", "Privacy", "Home")
        </li>*@
        <li>
            @Html.ActionLink("Aktualności1!!!!", "Aktualnosci", "Shared")
        </li>

        <li>
            @Html.ActionLink("Koszyk", "Index", "Sklep")
        </li>

        <li>
            @Html.ActionLink("Polityka prywatności", "Privacy", "Home")
        </li>

    </ul>

    <ul id="nav-mobile" class="sidenav">
        <li class="border border-dark black-text">@Html.ActionLink("Strona główna", "Index", "Home")</li>
        @foreach (var item in Model)
        {
            <li>
                @Html.ActionLink(item.Tytul, "Index", "Home", new { id = item.IdStrony }, null)
            </li>
        }
        <li>
            @Html.ActionLink("Koszyk", "Index", "Sklep")
        </li>
    </ul>
    <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
</div>

Firma.PortalWWW/Views/Shared/Parametry.cshtml
@model IEnumerable<Firma.Data.Data.CMS.Parametr>

    <div class="container">
        <div class="row">
            <div class="col l4 s12">
                <ul>
                @foreach (var item in Model)
                    if (item.Opis == "Footer1")
                    {
                        <li>@item.Nazwa</li>
                        <li>@item.Wartosc</li>
                    }
                </ul>
            </div>
            <div class="col l4 s12 black-text footer__text">
                <ul>
                    <li class="white-text">@Html.ActionLink("Strona główna", "Index", "Home")</li>
                    <li class="white-text">@Html.ActionLink("Polityka prywatności", "Privacy", "Home")</li>
                    <li class="white-text">@Html.ActionLink("O nas", "About", "Home")</li>
                </ul>
            </div>
            <div class="col l4 s12 white-text footer__text">
                <ul lass="link">
                    @foreach (var item in Model)
                        if (item.Opis == "Footer3")
                        {<li><a footer__text href="@item.Wartosc" class="white-text">@item.Nazwa</a></li>
                        }
                </ul>
            </div>
        </div>
    </div>

Firma.PortalWWW/Views/Shared/RodzajeMenu.cshtml
@model IEnumerable<Firma.Data.Data.CMS.Strona>
<div class="nav-wrapper">
    <a id="logo-container" href="#" class="brand-logo logo">
        <i class="material-icons">spa</i>Biblioteka
    </a>
    <ul class="right hide-on-med-and-down margin__right">
        <li class="border border-dark black-text">@Html.ActionLink("Strona główna", "Index", "Home")</li>
        @*@foreach (var item in Model)
        {
            <li>
                @Html.ActionLink(item.Tytul, "Index", "Home", new { id = item.IdStrony }, null)
            </li>
        }*@
        <li>
            @Html.ActionLink("Koszyk", "Index", "Sklep")
        </li>
        <li>
            <a href="@Url.Action("Index", "Koszyk")">
                <i class="material-icons">shopping_basket</i>
            </a>
        </li>

    </ul>

    <ul id="nav-mobile" class="sidenav">
        <li class="border border-dark black-text">@Html.ActionLink("Strona główna", "Index", "Home")</li>
        @*@foreach (var item in Model)
        {
            <li>
                @Html.ActionLink(item.Tytul, "Index", "Home", new { id = item.IdStrony }, null)
            </li>
        }*@
        <li>
            @Html.ActionLink("Koszyk", "Index", "Sklep")
        </li>
        <li>
            <a href="@Url.Action("Index", "Koszyk")">
                <i class="material-icons">shopping_basket</i>
            </a>
        </li>
    </ul>
    <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
</div>

Firma.PortalWWW/Views/Shared/Szczegoly.cshtml
@model Firma.Data.Data.Sklep.Produkt2
@{
    ViewData["Title"] = Model.Nazwa;
    Layout = "~/Views/Shared/_sklepLayout.cshtml";
}
<br>
<br>
<br>
@*<h2 class="header">Twoje rezerwacje</h2>*@
<div class="col s12 m7">
    <div class="card horizontal">
        <div class="card-image">
            <img src=@Model.FotoURL>
        </div>
        <div class="card-stacked">
            <div class="card-content">
                <table class="striped">
                    <tbody>
                        <tr>
                            <td>
                                <b>  Tytuł:</b>
                            </td>
                            <td>
                                @Model.Tytul
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <b>  Autor:</b>
                            </td>
                            <td>
                                @Model.Autor
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <b>Wydawnictwo:</b>
                            </td>
                            <td>
                                @Model.Wydawnictwo
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <b>Liczba pozycji:</b>
                            </td>
                            <td>
                                @Model.Ilosc
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <b>Streszczenie:</b>
                            </td>
                            <td>
                                @Model.Opis
                            </td>
                        </tr>
                        <tr>
                            <td>
                            </td>
                            <td>

                                <button class="btn pink darken-1 white-text" data-mdb-color="dark"> @Html.ActionLink("Dodaj do koszyka", "DodajDoKoszyka", "Koszyk", new { id = Model.IdProduktu2 }, "")</button>


                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Firma.PortalWWW/Views/Shared/Towary.cshtml
@model IEnumerable<Firma.Data.Data.Sklep.Produkt2>

<h3 class="center">Ostatnio dodane książki</h3>
@{
    var rowSize = 6;
    var rowCount = (Model.Count() / rowSize);
    // poniżej podział wszytskich produktów na wiersze
    //   if ((Model.Count() / rowSize) % rowSize != 0)
    //       rowCount = rowCount + 1;



    //style="width:240px; height:310px"
}



@for (var i = 0; i < 1; i++)
{
<div class="row g-0">

    @*@foreach (var item in Model.Skip(i * rowSize).Take(rowSize))*@

        @foreach (var item in Model.TakeLast(6))
        {
            <div class="col s12 m2">
                <div class="card medium">
                    <div class="card-image">
                        <img src=@item.FotoURL>
                    </div>
                    <div class="card-content">
                        <p>
                            @item.Tytul
                        </p>
                        <p>
                            @item.Autor
                        </p>
                        <div class=" card-action center-align">
                            <a class="btn pink darken-1" asp-action="Szczegoly" asp-route-id="@item.IdProduktu2">
                            Szczegóły</a>
                        </div>
                        <br />
                    </div>
                </div>
            </div>
        }
</div>
}

Firma.PortalWWW/Views/Shared/_KoszykLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Firma.PortalWWW</title>
    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous" />
    <link href="~/lib/materialize/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection" />

    <link href="~/css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="~/css/styleK.css" type="text/css" rel="stylesheet" media="screen,projection" />
</head>

<body>
    <nav class="black navK" role="navigation">
        @await Html.PartialAsync("RodzajeMenu", (IEnumerable<Firma.Data.Data.CMS.Strona>)ViewBag.ModelStrony)

        <ul class="right hide-on-med-and-down">
            <li>
                @Html.ActionLink("Powrót do sklepu", "Index", "Sklep")
            </li>
        </ul>

    </nav>

    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
            @RenderBody()
        </div>
    </div>

    <!-- Media spolecznosciowe -->
    <section class="section section-follow black darken-2 white-text">
        <div class="container">
            <div class="row">
                <div class="col s12 center">
                    <h4>Znajdziesz nas również</h4>
                    <p>Obserwuj nas na mediach społecznościowych</p>
                    <a href="#" class="white-text">
                        <i class="fab fa-facebook fa-4x"></i>
                    </a>
                    <a href="#" class="white-text">
                        <i class="fab fa-twitter fa-4x"></i>
                    </a>
                    <a href="#" class="white-text">
                        <i class="fab fa-linkedin fa-4x"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>


    <!-- Kontakt -->
    <section id="contact" class="section section-contact scrollspy">
        <div class="container">
            <div class="row">
                <form class="col s12">
                    <div class="row">
                        <div class="input-field col s6">
                            <i class="material-icons prefix">account_circle</i>
                            <input type="text" class="validate">
                            <label for="icon_prefix">Imię</label>
                        </div>
                        <div class="input-field col s6">
                            <i class="material-icons prefix">email</i>
                            <input type="email" class="validate">
                            <label for="icon_email">Email</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">message</i>
                            <textarea id="textarea1" class="materialize-textarea"></textarea>
                            <label for="icon_prefix">Wiadomość</label>
                        </div>
                    </div>
                    <input type="submit" value="Wyślij" class="black btn-large">
                </form>
            </div>
        </div>
    </section>


    <!-- Stopka -->
    <footer class="page-footer black text-white">
        @*   @await Html.PartialAsync("Parametry", (IEnumerable<Firma.Data.Data.CMS.Parametr>)ViewBag.ModelParametry)*@
        <div class="footer-copyright">
            <div class="container">
                Made by <a class="white-text text-lighten-3" href="http://materializecss.com">Materialize</a>
            </div>
        </div>
    </footer>

    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="~/lib/materialize/js/materialize.min.js"></script>
    <script src="~/js/init.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Firma.PortalWWW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Firma.PortalWWW</title>
    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="~/css/site.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="~/css/styleK.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="~/css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="~/lib/materialize/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection" />

</head>
<body>
    <nav class="black" role="navigation">
        @await Html.PartialAsync("Odnosniki", (IEnumerable<Firma.Data.Data.CMS.Strona>)ViewBag.ModelStrony)
    </nav>


    <div class="section sk" id="index-banner">
        <div>
            @RenderBody()
        </div>
    </div>
    <!-- Ostatnie publikacje -->
    <section class="section section-blog scrollspy ">
        @await Html.PartialAsync("Aktualnosci", (IEnumerable<Firma.Data.Data.CMS.Aktualnosc>)ViewBag.ModelAktualnosci)
    </section>
    <!-- Ostatnie publikacje -->
    <section class="section section-blog scrollspy ">
        @await Html.PartialAsync("Towary", (IEnumerable<Firma.Data.Data.Sklep.Produkt2>)ViewBag.ModelProdukty2)
    </section>
    <!-- Media spolecznosciowe -->
    <section class="section section-follow black darken-2 white-text">
        <div class="container">
            <div class="row">
                <div class="col s12 center">
                    <h4>Znajdziesz nas również</h4>
                    <p>Obserwuj nas na mediach społecznościowych</p>
                    <a href="#" class="white-text">
                        <i class="fab fa-facebook fa-4x"></i>
                    </a>
                    <a href="#" class="white-text">
                        <i class="fab fa-twitter fa-4x"></i>
                    </a>
                    <a href="#" class="white-text">
                        <i class="fab fa-linkedin fa-4x"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>


    <!-- Kontakt -->
    <section id="contact" class="section section-contact scrollspy">
        <div class="container">
            <div class="row">
                <form class="col s12">
                    <div class="row">
                        <div class="input-field col s6">
                            <i class="material-icons prefix">account_circle</i>
                            <input type="text" class="validate">
                            <label for="icon_prefix">Imię</label>
                        </div>
                        <div class="input-field col s6">
                            <i class="material-icons prefix">email</i>
                            <input type="email" class="validate">
                            <label for="icon_email">Email</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">message</i>
                            <textarea id="textarea1" class="materialize-textarea"></textarea>
                            <label for="icon_prefix">Wiadomość</label>
                        </div>
                    </div>
                    <input type="submit" value="Wyślij" class="black btn-large">
                </form>
            </div>
        </div>
    </section>

    <!-- Stopka -->
    <footer class="page-footer black text-white">
        @await Html.PartialAsync("Parametry", (IEnumerable<Firma.Data.Data.CMS.Parametr>)ViewBag.ModelParametry)
        @*<div class="container">
                <div class="row">
                    <div class="col l4 s12">
                        E-mail<br>
                        sklep@wydawnictwo.com<br>
                        Telefon<br>
                        +48 987 654 321
                    </div>
                    <div class="col l4 s12 black-text footer__text">
                        <ul>
                            <li class="link">@Html.ActionLink("Strona główna", "Index", "Home")</li>
                            <li class="link">@Html.ActionLink("Polityka prywatności", "Privacy", "Home")</li>
                            <li class="link">@Html.ActionLink("O nas", "About", "Home")</li>
                        </ul>
                    </div>
                    <div class="col l4 s12 black-text footer__text">
                        <ul lass="link">
                            <li lass="link">
                                <a footer__text href="https://www.facebook.com/" class="link">Facebook</a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/" class="link">Instagram</a>
                            </li>
                            <li>
                                <a href="https://www.youtube.com/" class="link">YouTube</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>*@

        <div class="footer-copyright">
            <div class="container">
                Made by <a class="white-text text-lighten-3" href="http://materializecss.com">Materialize</a>
            </div>
        </div>
    </footer>
    <!--  Scripts-->
    <script src="~/lib/materialize/js/materialize.js" type="text/javascript"></script>
    <script src="~/js/init.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>
    <script src="~/lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="~/js/site.js" asp-append-version="true" type="text/javascript"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Firma.PortalWWW/Views/Shared/_sklepLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Firma.PortalWWW</title>
    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
          crossorigin="anonymous" />
    <link href="~/lib/materialize/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="~/css/style.css" type="text/css" rel="stylesheet" media="screen,projection" />
    <link href="~/css/styleK.css" type="text/css" rel="stylesheet" media="screen,projection" />
</head>
<body>
    <nav class="black navK" role="navigation">
        @await Html.PartialAsync("RodzajeMenu", (IEnumerable<Firma.Data.Data.CMS.Strona>)ViewBag.ModelStrony)
    </nav>

    <div class="section no-pad-bot" id="index-banner">
        <div class="container">
            @RenderBody()
        </div>
    </div>

    <!-- Media spolecznosciowe -->
    <section class="section section-follow black darken-2 white-text">
        <div class="container">
            <div class="row">
                <div class="col s12 center">
                    <h4>Znajdziesz nas również</h4>
                    <p>Obserwuj nas na mediach społecznościowych</p>
                    <a href="#" class="white-text">
                        <i class="fab fa-facebook fa-4x"></i>
                    </a>
                    <a href="#" class="white-text">
                        <i class="fab fa-twitter fa-4x"></i>
                    </a>
                    <a href="#" class="white-text">
                        <i class="fab fa-linkedin fa-4x"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>


    <!-- Kontakt -->
    <section id="contact" class="section section-contact scrollspy">
        <div class="container">
            <div class="row">
                <form class="col s12">
                    <div class="row">
                        <div class="input-field col s6">
                            <i class="material-icons prefix">account_circle</i>
                            <input type="text" class="validate">
                            <label for="icon_prefix">Imię</label>
                        </div>
                        <div class="input-field col s6">
                            <i class="material-icons prefix">email</i>
                            <input type="email" class="validate">
                            <label for="icon_email">Email</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">message</i>
                            <textarea id="textarea1" class="materialize-textarea"></textarea>
                            <label for="icon_prefix">Wiadomość</label>
                        </div>
                    </div>
                    <input type="submit" value="Wyślij" class="black btn-large">
                </form>
            </div>
        </div>
    </section>


    <!-- Stopka -->
    <footer class="page-footer black text-white">
        @*   @await Html.PartialAsync("Parametry", (IEnumerable<Firma.Data.Data.CMS.Parametr>)ViewBag.ModelParametry)*@
        <div class="footer-copyright">
            <div class="container">
                Made by <a class="white-text text-lighten-3" href="http://materializecss.com">Materialize</a>
            </div>
        </div>
    </footer>

    <!--  Scripts-->

    <script src="~/js/init.js" type="text/javascript"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>