Firma.PortalWWW/Controllers/KoszykController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Firma.Data.Data;
using Firma.PortalWWW.Models.Biblioteka;
using Firma.PortalWWW.Models.BusinessLogic;
using Microsoft.AspNetCore.Mvc;

namespace Firma.PortalWWW.Controllers
{
    public class KoszykController : Controller
    {
        private readonly FirmaContextB _context; // tak tworzymy połączenie z bazą danych
        public KoszykController(FirmaContextB context)
        {
            _context = context; // tu inicjalizujemy baze danych
        }
        //to jest funkcja która dostarcza dane do widokuprezentującego cały koszyk
        public async Task<IActionResult> Index()
        {
            KoszykB koszyk = new KoszykB(_context, this.HttpContext);
            //ten obiekt tworzony jest tylko po to żeby w jednym obiekcie do widoku przekazać dwa elementy: elementy koszyka, razem
            //do widoku można przekazać tylko 1 element!!!!!!! dlatego tworzymy klase ktora bedzie miala 2 elementy w sobie zeby moc je przakazac
            DaneDoKoszyka daneDoKoszyka = new DaneDoKoszyka
            {
                ElementyKoszykaB = await koszyk.GetElementyKoszyka(),
                // Razem = await koszyk.GetRazem()
                Rezerwacja = await koszyk.GetRezerwacja()
            };
            //przekazujemy dane do koszyka złozone z dwoch elementów do widoku
            return View(daneDoKoszyka);
        }
        //funkcja kontrolera dodaje towar do koszyka
        //to jest akcja, ktora zostanie wywołana pod przyciskiem dodaj do koszyka
        public async Task<ActionResult> DodajDoKoszyka(int id)
        {
            KoszykB koszyk = new KoszykB(_context, this.HttpContext);
            koszyk.DodajDoKoszyka(await _context.Produkt2.FindAsync(id));
            //po dodaniu towaru do koszyka przechodze do tego koszyka, czyli do Index, który wyswietli koszyk
            return RedirectToAction("Index");//to jest przejscie do widoku indeks
        }
    }
}

Firma.PortalWWW/Controllers/SklepController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Firma.Data.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Firma.PortalWWW.Controllers
{
    public class SklepController : Controller
    {
        private readonly FirmaContextB _context; // tak tworzymy połączenie z bazą danych
        public SklepController(FirmaContextB context)
        {
            _context = context; // tu inicjalizujemy baze danych
        }


        public async Task<IActionResult> Index(int? id) // w id będzie przechowywny id rodzaju którego towary mmy wyświetlić
        {
            //do ViewBag zapisuję wszystkie rodzaje z bazy danych asynchronicznie (musimy użyć using Microsoft.EntityFrameworkCore;)
            ViewBag.Rodzaje = await _context.Rodzaj.ToListAsync();


            ViewBag.ModelStrony =
              (
              from strona in _context.Strona // dla każdej strony z bazy danych stron
              orderby strona.Pozycja // posortowanej względem pozycji
              select strona // wybieramy stronę
              ).ToList();
            ViewBag.ModelAktualnosci =
                (
                from aktualnosc in _context.Aktualnosc // dla każdej strony z bazy danych stron
                orderby aktualnosc.Pozycja // posortowanej względem pozycji
                select aktualnosc // wybieramy stronę
                ).ToList();
            ViewBag.ModelParametry =
                (
                from parametr in _context.Parametr // dla każdej strony z bazy danych stron
                orderby parametr.IdParametru // posortowanej względem pozycji
                select parametr // wybieramy stronę
                ).ToList();
            ViewBag.ModelTowary =
                (
                from towar in _context.Towar // dla każdej strony z bazy danych stron
                orderby towar.IdTowaru // posortowanej względem pozycji
                select towar // wybieramy stronę
                ).ToList();

            ViewBag.ModelProdukty2 =
               (
               from produkt in _context.Produkt2 // dla każdej strony z bazy danych stron
               orderby produkt.IdProduktu2 // posortowanej względem pozycji
               select produkt // wybieramy stronę
               ).ToList();


            //przy pierwszym uruchomieniu sklepu nie ma wybranego rodzaju więc pod rodzaj podstawimy pierwszy rodzaj z bazy danych
            if (id == null)
            {
                var pierwszy = await _context.Rodzaj.FirstAsync();
                id = pierwszy.IdRodzaju;
            }
            //do widoku przekazuję wszytskie towary danego rodzaju ktróego mamy id asynchronicznie
            return View(await _context.Produkt2.Where(item => item.IdRodzaju == id).ToListAsync());
        }

        //funkcja zwraca do widoku towar o id danym jako parametr

        public async Task<IActionResult> Szczegoly(int id)
        {
            ViewBag.Rodzaje = await _context.Rodzaj.ToListAsync();
            return View(await _context.Produkt2.Where(t => t.IdProduktu2 == id).FirstOrDefaultAsync());
        }
    }
}

Firma.PortalWWW/Views/Sklep/Index.cshtml
@model IEnumerable<Firma.Data.Data.Sklep.Produkt2>
@{
    ViewData["Title"] = "Sklep";
    Layout = "~/Views/Shared/_sklepLayout.cshtml";
}

<div style="margin-top:60px">

    <table>
        <tbody>
            @foreach (var towar in Model)
            {
                <ul class="collection">
                    <li class="collection-item avatar">
                        <img src=@towar.FotoURL alt="" class="circle">
                        <p>
                            @towar.Tytul <br>
                            @towar.Autor <br>
                            @towar.Wydawnictwo <br>

                        </p>
                        <a asp-action="Szczegoly" asp-route-id="@towar.IdProduktu2" class="secondary-content">
                            <i class="btn pink darken-1">Szczegóły</i>
                        </a>
                    </li>
                </ul>
            }
        <tbody>
    <table>


</div>

Firma.PortalWWW/Views/Sklep/Szczegoly.cshtml
@model Firma.Data.Data.Sklep.Towar
@{
    ViewData["Title"] = Model.Nazwa;
    Layout = "~/Views/Shared/_sklepLayout.cshtml";
}
<br>
<br>
<br>
@*<h2 class="header">Twoje rezerwacje</h2>*@
<div class="col s12 m7">
    <div class="card horizontal">
        <div class="card-image">
            <img src=@Model.FotoURL>
        </div>
        <div class="card-stacked">
            <div class="card-content">
                <div>
                    @Model.Nazwa
                </div>
                <div>
                    @Model.Cena
                </div>
                <div>
                    @Model.Opis
                </div>
                <div>
                    @Html.ActionLink("DodajDoKoszyka", "DodajDoKoszyka", "Koszyk", new { id = Model.IdTowaru }, "")
                </div>
            </div>
        </div>
    </div>
</div>